// Theme color definitions that match globals.css
export const themeColors = {
  light: {
    mode: 'light' as const,
    primary: '#6366f1',
    secondary: '#f59e0b',
    background: '#f8fafc',
    paper: '#ffffff',
    text: '#0f172a',
    textSecondary: '#64748b',
  },
  dark: {
    mode: 'dark' as const,
    primary: '#6366f1',
    secondary: '#f59e0b',
    background: '#000000',
    paper: '#1a1a1a',
    text: '#ffffff',
    textSecondary: '#a3a3a3',
  },
  ocean: {
    mode: 'light' as const,
    primary: '#0ea5e9',
    secondary: '#06b6d4',
    background: '#f0f9ff',
    paper: '#ffffff',
    text: '#0c4a6e',
    textSecondary: '#0369a1',
  },
  forest: {
    mode: 'light' as const,
    primary: '#059669',
    secondary: '#10b981',
    background: '#f0fdf4',
    paper: '#ffffff',
    text: '#064e3b',
    textSecondary: '#047857',
  },
  sunset: {
    mode: 'light' as const,
    primary: '#ea580c',
    secondary: '#f97316',
    background: '#fff7ed',
    paper: '#ffffff',
    text: '#7c2d12',
    textSecondary: '#c2410c',
  },
  lavender: {
    mode: 'light' as const,
    primary: '#8b5cf6',
    secondary: '#a78bfa',
    background: '#faf5ff',
    paper: '#ffffff',
    text: '#581c87',
    textSecondary: '#7c3aed',
  },
  rose: {
    mode: 'light' as const,
    primary: '#ec4899',
    secondary: '#f472b6',
    background: '#fdf2f8',
    paper: '#ffffff',
    text: '#831843',
    textSecondary: '#be185d',
  },
  mint: {
    mode: 'light' as const,
    primary: '#10b981',
    secondary: '#34d399',
    background: '#ecfdf5',
    paper: '#ffffff',
    text: '#064e3b',
    textSecondary: '#047857',
  },
  amber: {
    mode: 'light' as const,
    primary: '#f59e0b',
    secondary: '#fbbf24',
    background: '#fffbeb',
    paper: '#ffffff',
    text: '#78350f',
    textSecondary: '#b45309',
  },
  slate: {
    mode: 'dark' as const,
    primary: '#64748b',
    secondary: '#94a3b8',
    background: '#0f172a',
    paper: '#1e293b',
    text: '#f1f5f9',
    textSecondary: '#cbd5e1',
  },
  crimson: {
    mode: 'dark' as const,
    primary: '#dc2626',
    secondary: '#ef4444',
    background: '#1a0000',
    paper: '#2d0a0a',
    text: '#fecaca',
    textSecondary: '#fca5a5',
  },
  emerald: {
    mode: 'dark' as const,
    primary: '#047857',
    secondary: '#059669',
    background: '#001a0f',
    paper: '#0a2d1f',
    text: '#a7f3d0',
    textSecondary: '#6ee7b7',
  },
  sapphire: {
    mode: 'dark' as const,
    primary: '#1d4ed8',
    secondary: '#2563eb',
    background: '#00001a',
    paper: '#0a1a2d',
    text: '#bfdbfe',
    textSecondary: '#93c5fd',
  },
  coral: {
    mode: 'light' as const,
    primary: '#f97316',
    secondary: '#fb923c',
    background: '#fff7ed',
    paper: '#ffffff',
    text: '#7c2d12',
    textSecondary: '#c2410c',
  },
  violet: {
    mode: 'dark' as const,
    primary: '#7c3aed',
    secondary: '#8b5cf6',
    background: '#1a001a',
    paper: '#2d0a2d',
    text: '#ddd6fe',
    textSecondary: '#c4b5fd',
  },
  gold: {
    mode: 'light' as const,
    primary: '#ca8a04',
    secondary: '#eab308',
    background: '#fefce8',
    paper: '#ffffff',
    text: '#713f12',
    textSecondary: '#a16207',
  },
  charcoal: {
    mode: 'dark' as const,
    primary: '#6b7280',
    secondary: '#9ca3af',
    background: '#111827',
    paper: '#1f2937',
    text: '#f3f4f6',
    textSecondary: '#d1d5db',
  },
  cherry: {
    mode: 'dark' as const,
    primary: '#be185d',
    secondary: '#db2777',
    background: '#1a0010',
    paper: '#2d0a1f',
    text: '#fce7f3',
    textSecondary: '#fbcfe8',
  },
};

export type ThemeName = keyof typeof themeColors;
