import type { MealType } from '@/lib/db/types';

export interface SeedRecipe {
  title: string;
  description: string;
  mealType: MealType;
  ingredients: string[];
  steps: string[];
  tags: string[];
}

export const RECIPES: SeedRecipe[] = [
  {
    title: 'Creamy Lemon Orzo with Skinless Chicken Thighs',
    mealType: 'dinner',
    description:
      'A light, lemony orzo dish with pan-seared skinless chicken thighs. Lower-calorie thanks to the skinless thighs and minimal cream.',
    ingredients: [
      '4 skinless boneless chicken thighs',
      '200g orzo',
      '1 lemon (zest and juice)',
      '2 cloves garlic, minced',
      '1 small onion, diced',
      '500ml chicken stock',
      '50g light cream cheese (or 50ml single cream)',
      'a handful of baby spinach',
      '2 tbsp olive oil',
      'salt, pepper, fresh parsley',
    ],
    steps: [
      'Season the chicken thighs with salt and pepper.',
      'Sear in olive oil over medium-high heat ~4 min per side until golden and cooked through. Rest.',
      'In the same pan, soften onion and garlic.',
      'Add orzo and toast for 1 minute.',
      'Pour in stock and lemon zest, simmer 8-10 min until orzo is al dente and stock is mostly absorbed.',
      'Stir in cream cheese, lemon juice, and spinach until wilted.',
      'Slice chicken, top the orzo, and garnish with parsley.',
    ],
    tags: ['chicken', 'low-calorie', 'pasta', 'weeknight'],
  },
  {
    title: 'Nandos Fakeaway with Sweet Potato Wedges and Tenderstem Broccoli',
    mealType: 'dinner',
    description:
      'Peri-peri chicken thighs with crispy sweet potato wedges and charred tenderstem - Nandos at home.',
    ingredients: [
      '6 skin-on bone-in chicken thighs',
      '3 tbsp peri-peri sauce',
      '2 large sweet potatoes, cut into wedges',
      '1 tbsp olive oil for the wedges',
      '1 tsp smoked paprika',
      '200g tenderstem broccoli',
      '1 tbsp olive oil for the broccoli',
      '1 lemon, halved',
      'salt and pepper',
    ],
    steps: [
      'Preheat oven to 200C.',
      'Toss sweet potato wedges with olive oil, smoked paprika and salt - spread on a tray.',
      'Rub chicken thighs all over with peri-peri sauce, place skin-up on a second tray.',
      'Roast both for 30-35 min, flipping wedges halfway, until chicken is cooked through and skin is crispy.',
      'In the last 5 min, blanch tenderstem in boiling water 2 min, then char in a hot pan with olive oil for 2-3 min.',
      'Serve with lemon halves to squeeze over.',
    ],
    tags: ['chicken', 'fakeaway', 'peri-peri', 'weeknight'],
  },
  {
    title: 'Slow-Cooked Beef Barbacoa',
    mealType: 'dinner',
    description:
      'Mexican-style slow-cooked shredded beef with chipotle, lime and adobo. Great for tacos, bowls, or burritos.',
    ingredients: [
      '1.2kg beef chuck or brisket, cut into large chunks',
      '3 chipotle peppers in adobo, chopped',
      '4 cloves garlic, minced',
      '1 tbsp ground cumin',
      '2 tsp dried oregano',
      '1 tsp ground cloves',
      '60ml lime juice',
      '60ml apple cider vinegar',
      '250ml beef stock',
      '3 bay leaves',
      '2 tbsp olive oil',
      '1 tsp salt',
      '1 tsp black pepper',
    ],
    steps: [
      'Pat beef dry, season with salt and pepper.',
      'Sear chunks in olive oil until browned all sides - work in batches.',
      'Transfer to slow cooker.',
      'Blend chipotles, garlic, cumin, oregano, cloves, lime juice, vinegar and beef stock until smooth.',
      'Pour over beef, add bay leaves.',
      'Cook on low 8 hours or high 4-5 hours until shreddable.',
      'Discard bay leaves, shred with two forks, return to the cooking liquid.',
      'Serve in tacos with coriander, diced onion and lime.',
    ],
    tags: ['beef', 'mexican', 'slow-cooker', 'meal-prep'],
  },
  {
    title: 'Chicken Breast Chow Mein',
    mealType: 'dinner',
    description:
      'Quick weeknight stir-fried noodles with chicken breast and crunchy veg in a soy-sesame sauce.',
    ingredients: [
      '2 chicken breasts, sliced thinly',
      '250g egg noodles',
      '1 red pepper, sliced',
      '1 carrot, julienned',
      '100g beansprouts',
      '3 spring onions, sliced',
      '2 cloves garlic, minced',
      '1 tbsp fresh ginger, grated',
      '3 tbsp soy sauce',
      '1 tbsp dark soy sauce',
      '1 tbsp oyster sauce',
      '1 tsp sesame oil',
      '1 tsp sugar',
      '2 tbsp vegetable oil',
      '1 tsp cornflour mixed with 2 tbsp water',
    ],
    steps: [
      'Cook noodles per packet, drain, toss with a little oil.',
      'Whisk soy sauces, oyster sauce, sesame oil and sugar in a bowl.',
      'Heat oil in a wok over high heat.',
      'Stir-fry chicken 2-3 min until just cooked, set aside.',
      'Add garlic and ginger to the wok for 20 seconds.',
      'Add carrot and pepper, stir-fry 1-2 min.',
      'Return chicken, add noodles, sauce, beansprouts and spring onions. Toss.',
      'Add cornflour slurry, toss to coat. Serve immediately.',
    ],
    tags: ['chicken', 'stir-fry', 'noodles', 'quick'],
  },
  {
    title: 'Nandos-Style Chicken Wrap',
    mealType: 'lunch',
    description:
      'Peri-peri chicken, salad and a tangy mayo wrapped in a warm flour tortilla - like the Nandos wrap menu.',
    ingredients: [
      '2 chicken breasts',
      '2 tbsp peri-peri sauce',
      '4 large flour tortillas',
      '4 leaves cos lettuce, shredded',
      '1 large tomato, sliced',
      '1/2 red onion, finely sliced',
      '100g cheddar, grated',
      '4 tbsp mayonnaise',
      '1 tsp peri-peri sauce for the mayo',
      '1 tbsp olive oil',
      'salt and pepper',
    ],
    steps: [
      'Butterfly the chicken breasts, season, rub with peri-peri sauce.',
      'Pan-fry in olive oil over medium-high 4 min per side until cooked through.',
      'Rest 5 min, slice.',
      'Mix mayo with 1 tsp peri-peri sauce.',
      'Warm tortillas in a dry pan.',
      'On each, spread peri mayo, layer lettuce, tomato, onion, sliced chicken and cheese.',
      'Wrap tightly, slice in half.',
    ],
    tags: ['chicken', 'wrap', 'fakeaway', 'lunch'],
  },
  {
    title: 'Bacon and Egg Bagel',
    mealType: 'breakfast',
    description:
      'Toasted bagel with crispy bacon, a fried egg, melted cheese and a smear of brown sauce.',
    ingredients: [
      '2 plain or sesame bagels, halved',
      '4 rashers smoked back bacon',
      '2 large eggs',
      '2 slices mature cheddar',
      '1 tbsp butter',
      '2 tbsp brown sauce or ketchup',
      'freshly ground black pepper',
    ],
    steps: [
      'Fry bacon in a dry pan until crispy, set aside.',
      'Toast the bagel halves.',
      'While they toast, fry the eggs in butter to your liking, runny yolks recommended.',
      'On the bottom half of each bagel, add cheese, bacon, the egg, a grind of pepper, then a smear of brown sauce on the top half.',
      'Close, eat.',
    ],
    tags: ['breakfast', 'bagel', 'bacon', 'quick'],
  },
  {
    title: 'Sushi Rice and Eggs',
    mealType: 'breakfast',
    description:
      'Japanese-inspired breakfast - sticky seasoned sushi rice topped with soft-set scrambled eggs, soy and furikake.',
    ingredients: [
      '200g sushi rice',
      '240ml water',
      '1 tbsp rice vinegar',
      '1 tsp sugar',
      '1/2 tsp salt',
      '4 large eggs',
      '1 tsp soy sauce',
      '1 tsp mirin',
      '1 tbsp butter',
      'furikake or toasted sesame seeds',
      '2 spring onions, sliced',
      'soy sauce to serve',
    ],
    steps: [
      'Rinse rice until water runs clear, then cook with the water in a rice cooker, or simmer covered 12 min then rest 10 min.',
      'Mix vinegar, sugar and salt, fold through cooked rice, let cool slightly.',
      'Beat eggs with soy and mirin.',
      'Melt butter in a non-stick pan over low heat, add eggs, stir gently with a spatula for soft-set scramble - do not overcook.',
      'Divide rice between two bowls, top with eggs, sprinkle furikake and spring onions, drizzle a little soy.',
    ],
    tags: ['breakfast', 'japanese', 'rice', 'eggs'],
  },
  {
    title: 'Classic Overnight Oats',
    mealType: 'breakfast',
    description:
      'The base recipe - creamy rolled oats soaked overnight in milk and yogurt, ready to grab in the morning.',
    ingredients: [
      '80g rolled oats',
      '200ml milk',
      '100g Greek yogurt',
      '1 tbsp honey or maple syrup',
      '1 tbsp chia seeds',
      '1/2 tsp vanilla extract',
      'pinch of salt',
    ],
    steps: [
      'Combine all ingredients in a jar or container.',
      'Stir well.',
      'Cover and refrigerate at least 4 hours, ideally overnight.',
      'In the morning, give it a stir, top with whatever you fancy such as berries, banana or nut butter, eat cold.',
    ],
    tags: ['breakfast', 'overnight-oats', 'meal-prep', 'make-ahead'],
  },
  {
    title: 'Peanut Butter and Banana Overnight Oats',
    mealType: 'breakfast',
    description: 'Overnight oats variant with peanut butter, banana and a hint of cinnamon.',
    ingredients: [
      '80g rolled oats',
      '200ml milk',
      '100g Greek yogurt',
      '2 tbsp peanut butter',
      '1 ripe banana, mashed',
      '1 tbsp honey',
      '1 tbsp chia seeds',
      '1/2 tsp ground cinnamon',
      'pinch of salt',
    ],
    steps: [
      'Mash the banana into the milk and peanut butter until smooth-ish.',
      'Stir in oats, yogurt, honey, chia, cinnamon and salt.',
      'Decant into a jar.',
      'Refrigerate overnight.',
      'Top with extra banana slices and a drizzle of peanut butter to serve.',
    ],
    tags: ['breakfast', 'overnight-oats', 'peanut-butter', 'make-ahead'],
  },
  {
    title: 'Berry and Almond Overnight Oats',
    mealType: 'breakfast',
    description: 'Overnight oats variant with mixed berries, almond butter and flaked almonds.',
    ingredients: [
      '80g rolled oats',
      '200ml almond milk',
      '100g Greek yogurt',
      '1 tbsp almond butter',
      '1 tbsp maple syrup',
      '1 tbsp chia seeds',
      '1/2 tsp vanilla extract',
      'pinch of salt',
      '80g mixed berries',
      '1 tbsp flaked almonds',
    ],
    steps: [
      'Stir oats, milk, yogurt, almond butter, maple syrup, chia, vanilla and salt together in a jar until combined.',
      'Refrigerate overnight.',
      'In the morning, top with mixed berries and flaked almonds.',
    ],
    tags: ['breakfast', 'overnight-oats', 'berries', 'make-ahead'],
  },
];
